export const preconditions = {
	"asthma": ["asthma", "wheeze", "bronchospasm"],
		"diabetes": ["diabetes", "insulin"],
		"heart disease": ["heart disease", "cardiovascular disease", "cardiomyopathy"],
		"kidney disease": ["kidney disease", "renal disease", "renal failure"],
		"liver disease": ["liver disease", "hepatic disease", "cirrhosis"],
		"lung disease": ["lung disease", "pulmonary disease", "chronic obstructive pulmonary disease"],
		"cancer": ["cancer", "malignancy", "tumor"],
		"autoimmune disorders": ["autoimmune", "lupus", "rheumatoid arthritis"],
		"neurological disorders": ["neurological", "parkinson's"],
		"mental health disorders": ["mental health"],
		"abdominal aortic aneurysm": ["abdominal aortic aneurysm"],
		"acne": ["acne", "pimples", "zits"],
		"acute cholecystitis": ["acute cholecystitis"],
		"acute lymphoblastic leukemia": ["acute lymphoblastic leukemia", "all"],
		"acute myeloid leukemia": ["acute myeloid leukemia", "aml"],
		"actinic keratoses": ["actinic keratoses", "solar keratoses"],
		"actinomycosis": ["actinomycosis"],
		"amyloidosis": ["amyloidosis"],
		"acute pancreatitis": ["acute pancreatitis"],
		"acanthosis nigricans": ["acanthosis nigricans"],
		"addison's disease": ["addison's disease", "primary adrenal insufficiency", "hypocortisolism"],
		"asperger's": ["asperger's", "asperger syndrome"],
		"allergic rhinitis": ["allergic rhinitis"],
		"allergies": ["allergies", "hypersensitivity"],
		"alzheimer's disease": ["alzheimer's disease"],
		"anal cancer": ["anal cancer"],
		"anaphylaxis": ["anaphylaxis", "anaphylactic shock"],
		"angioedema": ["angioedema"],
		"ankylosing spondylitis": ["ankylosing spondylitis"],
		"anorexia nervosa": ["anorexia nervosa", "anorexia"],
		"anxiety": ["anxiety", "worry", "stress"],
		"appendicitis": ["appendicitis"],
		"arthritis": ["arthritis"],
		"asbestosis": ["asbestosis"],
		"ataxia": ["ataxia"],
		"atopic eczema": ["atopic eczema", "atopic dermatitis"],
		"attention deficit hyperactivity disorder": ["attention deficit hyperactivity disorder", "adhd"],
		"autistic spectrum disorder": ["autistic spectrum disorder", "autism", "asd"],
		"bacterial vaginosis": ["bacterial vaginosis"],
		"benign prostate enlargement": ["benign prostate enlargement", "bph", "benign prostatic hyperplasia"],
		"cholangiocarcinoma": ["cholangiocarcinoma", "bile duct cancer"],
		"bronchiolitis": ["bronchiolitis"],
		"bipolar disorder": ["bipolar disorder", "manic depression", "bipolar affective disorder"],
		"blepharitis": ["blepharitis"],
		"bladder cancer": ["bladder cancer"],
		"blood poisoning": ["blood poisoning", "sepsis", "septicemia"],
		"basal cell carcinoma": ["basal cell carcinoma", "bcc"],
		"bone cancer": ["bone cancer"],
		"bowel cancer": ["bowel cancer", "colorectal cancer"],
		"bowel incontinence": ["bowel incontinence", "fecal incontinence"],
		"bowel polyps": ["bowel polyps", "colon polyps"],
		"brain stem death": ["brain stem death"],
		"brain tumours": ["brain tumours", "brain tumors"],
		"breast cancer": ["breast cancer"],
		"bronchiectasis": ["bronchiectasis"],
		"bronchitis": ["bronchitis"],
		"bulimia": ["bulimia", "bulimia nervosa"],
		"bunion": ["bunion", "hallux valgus"],
		"carcinoid syndrome": ["carcinoid syndrome"],
		"myalgic encephalomyelitis": ["myalgic encephalomyelitis", "chronic fatigue syndrome", "cfs"],
		"catarrh": ["catarrh"],
		"cellulitis": ["cellulitis"],
		"cerebral palsy": ["cerebral palsy"],
		"cytomegalovirus": ["cytomegalovirus", "cmv"],
		"cardiomyopathy": ["cardiomyopathy"],
		"creutzfeldt-jakob disease": ["creutzfeldt-jakob disease", "cjd", "prion disease"],
		"cervical cancer": ["cervical cancer"],
		"chest infection": ["chest infection"],
		"chest pain": ["chest pain", "angina"],
		"chickenpox": ["chickenpox", "varicella"],
		"chilblains": ["chilblains", "pernio"],
		"chlamydia": ["chlamydia"],
		"chronic kidney disease": ["chronic kidney disease", "ckd"],
		"chronic lymphocytic leukaemia": ["chronic lymphocytic leukaemia", "cll"],
		"chronic myeloid leukaemia": ["chronic myeloid leukaemia", "cml"],
		"chronic pancreatitis": ["chronic pancreatitis"],
		"clostridium difficile": ["clostridium difficile", "c. difficile", "c diff"],
		"coeliac disease": ["coeliac disease", "celiac disease"],
		"cold sore": ["cold sore", "herpes labialis"],
		"coma": ["coma"],
		"common cold": ["common cold", "cold", "upper respiratory tract infection"],
		"congenital heart disease": ["congenital heart disease", "chd"],
		"conjunctivitis": ["conjunctivitis", "pink eye"],
		"constipation": ["constipation"],
		"coronavirus": ["coronavirus", "covid-19", "sars-cov-2"],
		"cough": ["cough"],
		"crohn's disease": ["crohn's disease", "crohn disease"],
		"cushing syndrome": ["cushing syndrome", "cushing's syndrome", "hypercortisolism"],
		"croup": ["croup"],
		"cystic fibrosis": ["cystic fibrosis", "cf"],
		"cystitis": ["cystitis"],
		"deep vein thrombosis": ["deep vein thrombosis", "dvt"],
		"dehydration": ["dehydration"],
		"dementia": ["dementia"],
		"dental abscess": ["dental abscess", "tooth abscess"],
		"diabetes insipidus": ["diabetes insipidus"],
		"depression": ["depression", "major depressive disorder", "clinical depression"],
		"dermatitis herpetiformis": ["dermatitis herpetiformis"],
		"diarrhoea": ["diarrhoea", "diarrhea"],
		"discoid eczema": ["discoid eczema", "nummular eczema"],
		"diverticulitis": ["diverticulitis"],
		"dizziness": ["dizziness", "vertigo"],
		"down's syndrome": ["down's syndrome", "down syndrome", "trisomy 21"],
		"dry mouth": ["dry mouth", "xerostomia"],
		"dysphagia": ["dysphagia"],
		"dystonia": ["dystonia"],
		"earache": ["earache", "otalgia"],
		"ebola virus disease": ["ebola virus disease", "ebola", "ebola hemorrhagic fever"],
		"ectopic pregnancy": ["ectopic pregnancy"],
		"edwards' syndrome": ["edwards' syndrome", "trisomy 18"],
		"endometriosis": ["endometriosis"],
		"epilepsy": ["epilepsy"],
		"erectile dysfunction": ["erectile dysfunction", "impotence"],
		"escherichia coli": ["escherichia coli", "e. coli"],
		"ewing sarcoma": ["ewing sarcoma", "ewing's sarcoma"],
		"ehlers-danlos syndromes": ["ehlers-danlos syndromes", "eds"],
		"marfan syndrome": ["marfan syndrome"],
		"eye cancer": ["eye cancer", "ocular cancer"],
		"febrile seizures": ["febrile seizures", "febrile convulsions"],
		"fibroids": ["fibroids", "uterine fibroids", "leiomyomas"],
		"glomerulonephritis": ["glomerulonephritis"],
		"fibromyalgia": ["fibromyalgia"],
		"flatulence": ["flatulence", "gas"],
		"flu": ["flu", "influenza"],
		"fetal alcohol syndrome": ["fetal alcohol syndrome", "fas"],
		"food poisoning": ["food poisoning"],
		"functional neurological disorder": ["functional neurological disorder", "conversion disorder"],
		"fungal nail infection": ["fungal nail infection", "onychomycosis"],
		"gallbladder cancer": ["gallbladder cancer"],
		"gallstones": ["gallstones", "cholelithiasis"],
		"ganglion cyst": ["ganglion cyst"],
		"gastroenteritis": ["gastroenteritis", "stomach flu"],
		"gastroesophageal reflux disease": ["gastroesophageal reflux disease", "gerd", "acid reflux"],
		"gastritis": ["gastritis"],
		"genital herpes": ["genital herpes"],
		"genital warts": ["genital warts", "condyloma acuminatum"],
		"giant cell arteritis": ["giant cell arteritis", "temporal arteritis"],
		"giardiasis": ["giardiasis", "beaver fever"],
		"glandular fever": ["glandular fever", "infectious mononucleosis", "mono"],
		"glaucoma": ["glaucoma"],
		"gonorrhoea": ["gonorrhoea", "gonorrhea"],
		"gout": ["gout"],
		"granulomatosis with polyangiitis": ["granulomatosis with polyangiitis", "gpa", "wegener's granulomatosis"],
		"guillain-barré syndrome": ["guillain-barré syndrome", "gbs"],
		"gum disease": ["gum disease", "periodontal disease"],
		"haemorrhoids": ["haemorrhoids", "hemorrhoids", "piles"],
		"hay fever": ["hay fever", "allergic rhinitis"],
		"head lice": ["head lice", "pediculosis capitis"],
		"headache": ["headache"],
		"hearing loss": ["hearing loss", "hearing impairment"],
		"heart attack": ["heart attack", "myocardial infarction"],
		"heart failure": ["heart failure", "congestive heart failure"],
		"hepatitis A": ["hepatitis A"],
		"hepatitis B": ["hepatitis B"],
		"hepatitis C": ["hepatitis C"],
		"hiccups": ["hiccups", "hiccoughs"],
		"high blood pressure": ["high blood pressure", "hypertension"],
		"high cholesterol": ["high cholesterol", "hypercholesterolemia"],
		"hodgkin lymphoma": ["hodgkin lymphoma", "hodgkin's lymphoma"],
		"huntington's disease": ["huntington's disease", "huntington disease"],
		"hydrocephalus": ["hydrocephalus", "water on the brain"],
		"hyperglycaemia": ["hyperglycaemia", "high blood sugar"],
		"hyperhidrosis": ["hyperhidrosis", "excessive sweating"],
		"hypoglycaemia": ["hypoglycaemia", "low blood sugar"],
		"hypothermia": ["hypothermia"],
		"impetigo": ["impetigo"],
		"indigestion": ["indigestion", "dyspepsia"],
		"infertility": ["infertility"],
		"inguinal hernia": ["inguinal hernia"],
		"insomnia": ["insomnia"],
		"irritable bowel syndrome": ["irritable bowel syndrome", "ibs"],
		"iron deficiency anaemia": ["iron deficiency anaemia", "iron deficiency anemia"],
		"irritable hip": ["irritable hip", "transient synovitis"],
		"jaundice": ["jaundice"],
		"kidney cancer": ["kidney cancer", "renal cancer"],
		"kidney infection": ["kidney infection", "pyelonephritis"],
		"kidney stones": ["kidney stones", "nephrolithiasis", "renal calculi"],
		"labyrinthitis": ["labyrinthitis"],
		"lactose intolerance": ["lactose intolerance"],
		"laryngeal cancer": ["laryngeal cancer"],
		"laryngitis": ["laryngitis"],
		"leg cramps": ["leg cramps"],
		"lichen planus": ["lichen planus"],
		"liver cancer": ["liver cancer", "hepatic cancer"],
		"liver failure": ["liver failure"],
		"lung cancer": ["lung cancer"],
		"lupus": ["lupus", "systemic lupus erythematosus", "sle"],
		"lyme disease": ["lyme disease", "borreliosis"],
		"lymphedema": ["lymphedema", "lymphoedema"],
		"lymphoma": ["lymphoma"],
		"malaria": ["malaria"],
		"male breast cancer": ["male breast cancer"],
		"measles": ["measles", "rubeola"],
		"meningitis": ["meningitis"],
		"menopause": ["menopause"],
		"migraine": ["migraine"],
		"miscarriage": ["miscarriage"],
		"motor neurone disease": ["motor neurone disease", "mnd", "als", "amyotrophic lateral sclerosis"],
		"mouth cancer": ["mouth cancer", "oral cancer"],
		"mouth ulcers": ["mouth ulcers", "aphthous ulcers", "canker sores"],
		"multiple myeloma": ["multiple myeloma"],
		"multiple sclerosis": ["multiple sclerosis", "ms"],
		"mumps": ["mumps"],
		"muscular dystrophy": ["muscular dystrophy"],
		"myasthenia gravis": ["myasthenia gravis"],
		"myelodysplastic syndromes": ["myelodysplastic syndromes", "mds"],
		"myeloma": ["myeloma"],
		"narcolepsy": ["narcolepsy"],
		"nasal polyps": ["nasal polyps"],
		"nasopharyngeal cancer": ["nasopharyngeal cancer"],
		"night sweats": ["night sweats"],
		"non-alcoholic fatty liver disease": ["non-alcoholic fatty liver disease", "nafld"],
		"non-hodgkin lymphoma": ["non-hodgkin lymphoma", "nhl"],
		"norovirus": ["norovirus", "winter vomiting bug"],
		"obesity": ["obesity"],
		"obsessive compulsive disorder": ["obsessive compulsive disorder", "ocd"],
		"osteoporosis": ["osteoporosis"],
		"ovarian cancer": ["ovarian cancer"],
		"ovarian cyst": ["ovarian cyst"],
		"pancreatic cancer": ["pancreatic cancer"],
		"pancreatitis": ["pancreatitis"],
		"panic disorder": ["panic disorder"],
		"parkinson's disease": ["parkinson's disease", "parkinson disease"],
		"pelvic inflammatory disease": ["pelvic inflammatory disease", "pid"],
		"peptic ulcer": ["peptic ulcer"],
		"peripheral neuropathy": ["peripheral neuropathy"],
		"perinatal depression": ["perinatal depression", "postpartum depression", "postnatal depression"],
		"personality disorders": ["personality disorders"],
		"pertussis": ["pertussis", "whooping cough"],
		"piles": ["piles", "hemorrhoids", "haemorrhoids"],
		"pityriasis rosea": ["pityriasis rosea"],
		"pityriasis versicolor": ["pityriasis versicolor", "tinea versicolor"],
		"pleurisy": ["pleurisy"],
		"pneumonia": ["pneumonia"],
		"polycystic ovary syndrome": ["polycystic ovary syndrome", "pcos"],
		"post-traumatic stress disorder": ["post-traumatic stress disorder", "ptsd"],
		"postnatal depression": ["postnatal depression", "postpartum depression"],
		"pregnant": ["pregnant", "pregnancy"],
		"premenstrual syndrome": ["premenstrual syndrome", "pms"],
		"prostate cancer": ["prostate cancer"],
		"psoriasis": ["psoriasis"],
		"psoriatic arthritis": ["psoriatic arthritis"],
		"pulmonary embolism": ["pulmonary embolism", "pe"],
		"pyelonephritis": ["pyelonephritis", "kidney infection"],
		"rabies": ["rabies"],
		"raynaud's phenomenon": ["raynaud's phenomenon", "raynaud's disease", "raynaud's syndrome"],
		"reactive arthritis": ["reactive arthritis"],
		"restless legs syndrome": ["restless legs syndrome", "rls"],
		"retinoblastoma": ["retinoblastoma"],
		"rheumatoid arthritis": ["rheumatoid arthritis", "ra"],
		"rickets": ["rickets"],
		"rosacea": ["rosacea"],
		"scabies": ["scabies"],
		"scarlet fever": ["scarlet fever"],
		"schizophrenia": ["schizophrenia"],
		"sciatica": ["sciatica"],
		"scoliosis": ["scoliosis"],
		"septic shock": ["septic shock"],
		"sexually transmitted infections": ["sexually transmitted infections", "stis"],
		"shingles": ["shingles", "herpes zoster"],
		"sickle cell anaemia": ["sickle cell anaemia", "sickle cell anemia"],
		"sinusitis": ["sinusitis"],
		"sjogren's syndrome": ["sjogren's syndrome"],
		"skin cancer": ["skin cancer"],
		"sleep apnea": ["sleep apnea", "sleep apnoea", "obstructive sleep apnea", "osa"],
		"slipped disc": ["slipped disc", "herniated disc", "ruptured disc"],
		"snoring": ["snoring"],
		"stomach cancer": ["stomach cancer", "gastric cancer"],
		"stomach ulcer": ["stomach ulcer", "peptic ulcer"],
		"stress incontinence": ["stress incontinence"],
		"stroke": ["stroke", "cerebrovascular accident", "cva"],
		"stye": ["stye", "hordeolum"],
		"subarachnoid hemorrhage": ["subarachnoid hemorrhage", "subarachnoid haemorrhage"],
		"sudden infant death syndrome": ["sudden infant death syndrome", "sids", "cot death"],
		"systemic lupus erythematosus": ["systemic lupus erythematosus", "lupus", "sle"],
		"tendinitis": ["tendinitis", "tendonitis"],
		"testicular cancer": ["testicular cancer"],
		"tinnitus": ["tinnitus"],
		"tonsillitis": ["tonsillitis"],
		"tooth decay": ["tooth decay", "dental caries", "cavities"],
		"toothache": ["toothache", "dental pain"],
		"transient ischaemic attack": ["transient ischaemic attack", "tia", "mini-stroke"],
		"trichomoniasis": ["trichomoniasis", "trich"],
		"tuberculosis": ["tuberculosis", "tb"],
		"type 1 diabetes": ["type 1 diabetes", "diabetes mellitus type 1"],
		"type 2 diabetes": ["type 2 diabetes", "diabetes mellitus type 2"],
		"ulcerative colitis": ["ulcerative colitis"],
		"underactive thyroid": ["underactive thyroid", "hypothyroidism"],
		"urinary incontinence": ["urinary incontinence"],
		"urinary tract infection": ["urinary tract infection", "uti"],
		"uterine cancer": ["uterine cancer", "endometrial cancer"],
		"varicose veins": ["varicose veins"],
		"venous leg ulcer": ["venous leg ulcer"],
		"vertigo": ["vertigo"],
		"vitiligo": ["vitiligo"],
		"vulvodynia": ["vulvodynia"],
		"warts": ["warts"],
		"whooping cough": ["whooping cough", "pertussis"],
		"williams syndrome": ["williams syndrome", "williams-beuren syndrome"],
		"wilson's disease": ["wilson's disease", "wilson disease"],
		"yellow fever": ["yellow fever"],
		"zika virus": ["zika virus"],
}