export const symptoms = [
  'dizziness',
  'vertigo',
  'headache',
  'numbness of extremities',
  'tingling of extremities',
  'lack of coordination',
  'loss or memory',
  'tremors',
  'lack of comprehension',
  'depression',
  'anxiety',
  'sadness',
  'fatigue',
  'anger',
  'paranoid',
  'detachment',
  'burning eyes',
  'floaters',
  'itchy eyes',
  'blurry vision',
  'dry eyes',
  'excessive tearing',
  'macular degeneration',
  'glaucoma',
  'diabetic retinopathy',
  'cataracts',
  'Amblyopia ',
  'conjunctivitis',
  'stye',
  'Strabismus',
  'tinnitus',
  'hearing loss',
  'ear infection',
  'pressure in the ears',
  'ear discharge',
  'vertigo',
  'nasal congestion',
  'sneezing',
  'post nasal drip',
  'sinus pressure',
  'sinus pain',
  'stuffy nose',
  'runny nose',
  'loss of smell',
  'loss of taste',
  'sore throat',
  'loss of voice',
  'difficulty swallowing',
  'tonsilitis',
  'hoarseness of voice',
  'cough',
  'muscle cramping',
  'muscle ache',
  'muscle twitching',
  'muscle spasms',
  'bruising',
  'joint pain',
  'brusitis',
  'gout',
  'muscle strain',
  'osteoarthritis',
  'rheumatoid arthritis',
  'osteoporosis',
  'nausea',
  'vomiting',
  'diarrhea',
  'constipation',
  'abdominal pain',
  'heartburn',
  'bloating',
  'gastritis',
  'bloody stools',
  'mucous in stools',
  'hemorrhoids',
  'hiatal hernia',
  'rapid heart rate',
  'slow heart rate',
  'high blood pressure',
  'low blood pressure',
  'high cholesterol',
  'irregular heart rate',
  'chest pain',
  'shortness of breath with exertion',
  'wheezing',
  'heart palpitations',
  'shortness of breath at rest',
  'chest congestion',
  'urinary incontinence',
  'pain with urination',
  'burning with urination',
  'cloudy urine',
  'blood in urine',
  'overactive bladder',
  'hives',
  'rash',
  'heat rash',
  'contact dermatitis',
  'rosacea',
  'eczema',
  'psoriasis',
  'ringworm',
  'painful menses',
  'irregular menses',
  'breast tenderness',
  'pelvic pain',
  'bleeding inbetween menses',
  'PMS',
  'enlarged prostate',
  'pain with intercourse',
  'fever',
  'chills',
  'sleep apnea',
  'insomnia',
  'narcolepsy',
  'restless leg syndrome',
  'parasomia',
  'migraine',
  'neck pain',
  'leg pain',
  'arm pain',
  'hand pain',
  'back pain',
  'shoulder pain',
  'knee pain',
  'hip pain',
  'ear pain',
  'allergies',
  'anorexia',
  'light headedness',
  'cold intolerance',
  'heat intolerance',
  'weight loss',
  'weight gain',
  'vaginal discharge',
  'penile discharge',
  'jaundice',
  'painful lymph nodes',
  'bloody nose',
  'nasal discharge',
  'tooth ache',
  'belching',
  'flatulence',
  'hair loss',
  'abnormal hair growth',
  'fainting',
  'amenorrhea',
  'double vision',
  'bloody sputum',
  'urinary discharge',
  'acne',
  'ADD/ADHD',
  'vaginitis',
  'bowel incontinence',
  'cellulitis',
  'cold sore',
  'endometriosis',
  'erectile dysfunction',
  'fibroids',
  'food poisoning',
  'nail infection',
  'gum disease',
  'hyperhidrosis',
  'hypoglycemia',
  'hyperglycemia',
  'hyperglycemia',
  'hot flashes',
  'nightsweats',
  'thrush',
]
